### ISSUE TITLE
an odd loop when choosing option 2 too many times

### ISSUE THREAD

**Issue by m455** [m455/asciifarm#1]
;; issue:
right now if you keep choosing option 2, then try to use option 3
to close, you have to choose option 3 the same amount of times
that you have chosen option 2 in order to get out of a weird loop

**Comment by jmdejong** [comment]
You are now using recursion as a way of looping.
When doing this, it is very important to make sure that your code doesn't do anything after the recursive call is made.

Theoretically you nothing should happen, but you have a bug on line 79 `(if (!= menu-choice (and "1" "2" "3"))`.
What `and` does is check it's arguments and return the first falsey argument.
Since all your arguments are truthy, it will return the last one, so `"3"` in this case.
This means that this line is always the same as `(if (!= menu-choice "3")`.

To fix this you could change it into `(if (and (!= menu-choice "1")  (!= menu-choice  "2") (!= menu-choice  "3"))`.
Since this is quite long, it might be better to do something like `(if (not (in menu-choice ["1", "2", "3"]))`

I think the best solution is to use a `cond` expression instead of if statements.
See http://docs.hylang.org/en/stable/language/api.html#cond
`cond` is similar to how `if .. elif .. else` chains work in python.

**Comment by m455** [comment]
Thank you so much troido!! This has been a mystery to me regarding
scheme's/lisp-likes and you just helped me understand how to do so many
other things that I've had trouble with in my other projects!!

**Comment by m455** [comment]
alright, i've changed it all to use `(cond)` :). thanks so much for your help and advice!

**Comment by jmdejong** [comment]
Now that you are using `cond` you don't need the condition anymore in the last statement.

The last statement is always only executed if the statements above are false, so what you could just do is:

    (cond 
      [(= menu-choice "1") (do ...)]
      [(= menu-choice "2") (do ...)]
      [(= menu-choice "3") (do ...)]
      [True (do ...)])

**Comment by m455** [comment]
Thanks again! All fixed!
